create:
  handler: app/sensor/create/index.handler
  iamRoleStatements:
    Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}
  memorySize: 256
  timeout: 10
  package:
    individually: true
    exclude:
      - app/**
    include:
      - app/sensor/create/index.js
      - app/helper/dynamodb.js
  events:
    - http:
        path: /api/v1/sensors
        method: post
        cors: true
        authorizer: authorize
