get:
  handler: app/src/sensors/main/get.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}        
  package:
    individually: true
    exclude:
      - app/src/**
    include:
      - app/src/sensors/main/get.js
      - app/helper/dynamodb_client/index.js
  events:
    - http:
        path: /api/v1/events/sensors/{id}
        method: get
        cors:
          origins: 
            - "*"
          headers:
            - Content-Type
            - Authorization
        authorizer:
          name: authorize
          resultTtlInSeconds: 30
          identitySource: method.request.header.Authorization
          type: request
