get:
  handler: app/src/sensors/main/get.handler
  iamRoleStatementsName: permitOnlyGet #optional custom role name setting instead of the default generated one 
  iamRoleStatements:
    - Effect: "Allow"        
      Action:
        - dynamodb:GetItem        
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  package:
    individually: true
    exclude:
      - app/**
    include:
      - app/src/sensors/main/get.js
      - app/schema/sensor.js
  events:
    - http:
        path: /api/v1/sensor/{sensorId}
        method: get
        cors:
          origins: 
            - "*"
          headers:
            - Content-Type
            - Authorization
        authorizer:
          name: authorize
          resultTtlInSeconds: 30
          identitySource: method.request.header.Authorization
          type: request
