delete:
  handler: app/src/sensors/main/delete.handler
  iamRoleStatementsName: permitOnlyDelete #optional custom role name setting instead of the default generated one 
  iamRoleStatements:
    - Effect: "Allow"        
      Action:
        - dynamodb:DeleteItem        
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  package:
    individually: true
    exclude:
      - app/**
    include:
      - app/src/sensors/main/delete.js
      - app/src/sensors/model/delete.js
      - app/src/sensors/controller/delete.js
      - app/schema/sensor.js
  events:
    - http:
        path: /api/v1/sensor/{sensorId}
        method: delete
        cors:
          origins: 
            - "*"
          headers:
            - Content-Type
            - Authorization
        authorizer:
          name: authorize
          resultTtlInSeconds: 30
          identitySource: method.request.header.Authorization
          type: request
