list:
  handler: app/src/sensors/main/list.handler
  iamRoleStatementsName: permitOnlyScan #optional custom role name setting instead of the default generated one 
  iamRoleStatements:
    - Effect: "Allow"        
      Action:
        - dynamodb:Scan        
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  package:
    individually: true
    exclude:
      - app/**
    include:
      - app/src/sensors/main/list.js
      - app/src/sensors/model/list.js
      - app/src/sensors/controller/list.js
      - app/schema/sensor.js
  events:
    - http:
        path: /api/v1/sensors
        method: post
        cors:
          origins: 
            - "*"
          headers:
            - Content-Type
            - Authorization
        authorizer:
          name: authorize
          resultTtlInSeconds: 30
          identitySource: method.request.header.Authorization
          type: request
