notify:
  handler: app/src/streams/dynamodb/index.handler
  iamRoleStatementsName: permitReadingStreamAndSNSPublish
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:  "arn:aws:lambda:${self:provider.region}:*:function:notify"
    - Effect: "Allow"
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:  "arn:aws:logs:${self:provider.region}:*:*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:  "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/stream/*"
    - Effect: "Allow"        
      Action:
        - sns:Publish
      Resource: "*"
  package:
    individually: true
    exclude:
      - app/**
    include:
      - app/src/streams/dynamodb/index.js
      - app/src/streams/dynamodb/publish.js
      - app/src/streams/dynamodb/slack.js
