authorize:
  handler: app/authorizer/index.handler
  environment:
    SECRET_KEY: ${ssm:/mySense/Secrets/dev~true}
  package:
    individually: true
    exclude:
      - app/**
    include:
      - app/authorizer/index.js
      - app/authorizer/policy.js