Resources:
  SensorDataTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TABLE}
      AttributeDefinitions:
        -
          AttributeName: sensorId
          AttributeType: S
      KeySchema:
        -
          AttributeName: sensorId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: OLD_IMAGE
  SensorDataTableStream:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn: { Fn::GetAtt: ['${self:provider.environment.DYNAMODB_TABLE}' , 'StreamArn'] }
      FunctionName: ${self:service.name}-${self:provider.stage}-notify
      StartingPosition: LATEST