Resources:
  SensorDataTable:
    Type: 'AWS::DynamoDB::Table'
    TableName: ${self:provider.environment.DYNAMODB_TABLE}
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: sensorId
          AttributeType: S
      KeySchema:
        -
          AttributeName: sensorId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
